-- all accounts (checking, savings, brokerage, etc.)
CREATE TABLE Accounts (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Name TEXT NOT NULL UNIQUE,
  -- CHECKING, SAVINGS, BROKERAGE, 401K, ROTH_IRA, TRADITIONAL_IRA, CREDIT_CARD
  Type TEXT NOT NULL
);

-- cash movements
CREATE TABLE Transactions (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  AccountId INTEGER NOT NULL REFERENCES Accounts (Id) ON DELETE CASCADE,
  -- DEPOSIT, WITHDRAWAL
  Type TEXT NOT NULL,
  Amount REAL NOT NULL,
  ExternalId TEXT NOT NULL UNIQUE,
  Merchant TEXT NOT NULL,
  TransactionTimestamp INTEGER NOT NULL,
  CommitTimestamp INTEGER NOT NULL
);

-- current share positions
CREATE TABLE Holdings (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  AccountId INTEGER NOT NULL REFERENCES Accounts (Id) ON DELETE CASCADE,
  Ticker TEXT NOT NULL,
  Shares REAL NOT NULL,
  UNIQUE (AccountId, Ticker)
);

-- investment movements
CREATE TABLE Trades (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  AccountId INTEGER NOT NULL REFERENCES Accounts (Id) ON DELETE CASCADE,
  -- BUY, SELL
  Type TEXT NOT NULL,
  Ticker TEXT NOT NULL,
  Shares REAL NOT NULL,
  Price REAL NOT NULL,
  Description TEXT,
  TradeTimestamp INTEGER NOT NULL,
  CommitTimestamp INTEGER NOT NULL
);
