cc_library(
    name = "handlers",
    visibility = ["//visibility:public"],
    deps = [
        "//vigil/handlers/api/accounts:create_account_handler",
        "//vigil/handlers/api/accounts:delete_account_handler",
        "//vigil/handlers/api/accounts:get_account_handler",
        "//vigil/handlers/api/accounts:list_accounts_handler",
        "//vigil/handlers/api/transactions:list_transactions_handler",
        "//vigil/handlers/api/trades:create_trade_handler",
        "//vigil/handlers/api/trades:list_trades_handler",
        "//vigil/handlers/api/holdings:get_holding_handler",
        "//vigil/handlers/api/holdings:list_holdings_handler",
        "//vigil/handlers/pages:health_handler",
        "//vigil/handlers/pages:index_handler",
        "//vigil/handlers/pages:get_new_account_handler",
    ],
)
